prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    retention: 2d
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 768Mi

grafana:
  defaultDashboardsEnabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

nodeExporter:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

defaultRules:
  rules:
    nodeExporterAlerting: false
    nodeExporterRecording: false
    node: false
    network: false
    kubePrometheusNodeRecording: false
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    windows: false
