tempo:
  memBallastSizeMbs: 256
  retention: 24h
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write"
    processor:
      service_graphs:
        wait: 10s
        max_items: 10000
      span_metrics:
        enable_target_info: true
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

persistence:
  size: 5Gi
